name: nkocr
channels:
  - defaults
dependencies:
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1
  - sqlite=3.36.0
  - tk=8.6.10
  - tzdata=2021a
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - argcomplete==3.1.6
      - backports-tarfile==1.1.0
      - beautifulsoup4==4.12.3
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - commitizen==3.10.0
      - decli==0.6.1
      - distlib==0.3.8
      - docutils==0.21.1
      - editdistpy==0.1.4
      - exceptiongroup==1.2.1
      - filelock==3.13.4
      - gdown==5.1.0
      - identify==2.5.35
      - idna==3.7
      - importlib-metadata==6.11.0
      - imutils==0.5.4
      - iniconfig==2.0.0
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - keyring==25.1.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - nh3==0.2.17
      - nkocr==2.4.2
      - nodeenv==1.8.0
      - numpy==1.26.0
      - opencv-contrib-python==4.10.0.84
      - packaging==24.0
      - pillow==10.3.0
      - pkginfo==1.10.0
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - pre-commit==3.4.0
      - prompt-toolkit==3.0.36
      - pygments==2.17.2
      - pysocks==1.7.1
      - pytesseract==0.3.10
      - pytest==8.1.1
      - pytest-socket==0.6.0
      - pyyaml==6.0.1
      - questionary==2.0.1
      - readme-renderer==43.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.7.1
      - scikit-learn==1.3.1
      - scipy==1.13.0
      - setuptools==65.5.0
      - six==1.16.0
      - soupsieve==2.5
      - symspellpy==6.7.7
      - termcolor==2.4.0
      - tesseract==0.1.3
      - threadpoolctl==3.4.0
      - tomli==2.0.1
      - tomlkit==0.12.4
      - tqdm==4.66.2
      - twine==5.0.0
      - urllib3==2.2.1
      - virtualenv==20.25.3
      - wcwidth==0.2.13
      - wheel==0.38.0
      - zipp==3.18.1
