name: nkocr
channels:
  - defaults
dependencies:
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.10
  - tzdata=2021a
  - wheel=0.41.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - attrs==21.2.0
      - charset-normalizer==2.0.6
      - commitizen==3.10.0
      - filelock==3.1.0
      - gdown==4.7.1
      - idna==3.2
      - imutils==0.5.4
      - iniconfig==1.1.1
      - joblib==1.0.1
      - numpy==1.26.0
      - opencv-contrib-python==4.5.3.56
      - packaging==21.0
      - pillow==10.0.1
      - pluggy==1.0.0
      - py==1.10.0
      - pyparsing==2.4.7
      - pysocks==1.7.1
      - pytesseract==0.3.10
      - pytest==6.2.5
      - pytest-socket==0.6.0
      - requests==2.31.0
      - scikit-learn==1.3.1
      - scipy==1.7.1
      - six==1.16.0
      - symspellpy==6.7.7
      - tesseract==0.1.3
      - threadpoolctl==2.2.0
      - toml==0.10.2
      - tqdm==4.62.3
      - urllib3==1.26.7
