package:
  name: nkocr
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/Lucs1590/Nkocr

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python>=3.6
    - tesseract
    - pytesseract
    - requests
    - wheel
    - pillow
    - numpy
    - scikit-learn
  run:
    - python>=3.6
    - tesseract
    - pytesseract
    - requests
    - wheel
    - pillow
    - numpy
    - scikit-learn

test:
  imports:
    - nkocr

about:
  home: https://github.com/Lucs1590/Nkocr
  license: Apache-2.0
  license_file: LICENSE
  summary: This module performs specific OCRs for food products and nutritional tables.

extra:
  recipe-maintainers:
    - Lucs1590
