name: EthicalCheck-Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 10 * * 5"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
       - name: Upload sarif file to repository
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif-result-file: "ethicalcheck-results.sarif"
          sarif_file: ./ethicalcheck-results.sarif

