# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy-pip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine Commitizen

      - name: Tweak tests and Update Version
        run: |
          sed 's/import src.auxiliary /import auxiliary /' -i src/ocr_product.py
          sed 's/import src.auxiliary /import auxiliary /' -i src/ocr_table.py

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

  deploy-conda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: publish-to-conda
        uses: maxibor/conda-package-publish-action@v1.1
        with:
          subDir: "conda"
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
